services:
  analiseia:
    build: .
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy}
  grobid:
    image: lfoppiano/grobid:0.8.0
    ports:
      - "8070:8070"
